// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type           = component.MustNewType("hp_printers")
	DeprecatedType = component.MustNewType("hpprinters")
	ScopeName      = "hpprintersreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
