// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	conventions "go.opentelemetry.io/otel/semconv/v1.40.0"
)

// AttributePrinterCartridgeColor specifies the value printer.cartridge.color attribute.
type AttributePrinterCartridgeColor int

const (
	_ AttributePrinterCartridgeColor = iota
	AttributePrinterCartridgeColorCyan
	AttributePrinterCartridgeColorMagenta
	AttributePrinterCartridgeColorYellow
	AttributePrinterCartridgeColorBlack
)

// String returns the string representation of the AttributePrinterCartridgeColor.
func (av AttributePrinterCartridgeColor) String() string {
	switch av {
	case AttributePrinterCartridgeColorCyan:
		return "cyan"
	case AttributePrinterCartridgeColorMagenta:
		return "magenta"
	case AttributePrinterCartridgeColorYellow:
		return "yellow"
	case AttributePrinterCartridgeColorBlack:
		return "black"
	}
	return ""
}

// MapAttributePrinterCartridgeColor is a helper map of string to AttributePrinterCartridgeColor attribute value.
var MapAttributePrinterCartridgeColor = map[string]AttributePrinterCartridgeColor{
	"cyan":    AttributePrinterCartridgeColorCyan,
	"magenta": AttributePrinterCartridgeColorMagenta,
	"yellow":  AttributePrinterCartridgeColorYellow,
	"black":   AttributePrinterCartridgeColorBlack,
}

var MetricsInfo = metricsInfo{
	PrinterCartridgeLeft: metricInfo{
		Name: "printer.cartridge.left",
	},
	PrinterUsageCopy: metricInfo{
		Name: "printer.usage.copy",
	},
	PrinterUsagePrint: metricInfo{
		Name: "printer.usage.print",
	},
	PrinterUsageScan: metricInfo{
		Name: "printer.usage.scan",
	},
}

type metricsInfo struct {
	PrinterCartridgeLeft metricInfo
	PrinterUsageCopy     metricInfo
	PrinterUsagePrint    metricInfo
	PrinterUsageScan     metricInfo
}

type metricInfo struct {
	Name string
}

type metricPrinterCartridgeLeft struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills printer.cartridge.left metric with initial data.
func (m *metricPrinterCartridgeLeft) init() {
	m.data.SetName("printer.cartridge.left")
	m.data.SetDescription("Percent of cartridge left")
	m.data.SetUnit("percent_100")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPrinterCartridgeLeft) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, printerCartridgeColorAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("printer.cartridge.color", printerCartridgeColorAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPrinterCartridgeLeft) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPrinterCartridgeLeft) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPrinterCartridgeLeft(cfg MetricConfig) metricPrinterCartridgeLeft {
	m := metricPrinterCartridgeLeft{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPrinterUsageCopy struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills printer.usage.copy metric with initial data.
func (m *metricPrinterUsageCopy) init() {
	m.data.SetName("printer.usage.copy")
	m.data.SetDescription("Cumulative of pages copied")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPrinterUsageCopy) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, printerPaperSizeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("printer.paper.size", printerPaperSizeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPrinterUsageCopy) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPrinterUsageCopy) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPrinterUsageCopy(cfg MetricConfig) metricPrinterUsageCopy {
	m := metricPrinterUsageCopy{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPrinterUsagePrint struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills printer.usage.print metric with initial data.
func (m *metricPrinterUsagePrint) init() {
	m.data.SetName("printer.usage.print")
	m.data.SetDescription("Cumulative of pages printed")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPrinterUsagePrint) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, printerPaperSizeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("printer.paper.size", printerPaperSizeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPrinterUsagePrint) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPrinterUsagePrint) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPrinterUsagePrint(cfg MetricConfig) metricPrinterUsagePrint {
	m := metricPrinterUsagePrint{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPrinterUsageScan struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills printer.usage.scan metric with initial data.
func (m *metricPrinterUsageScan) init() {
	m.data.SetName("printer.usage.scan")
	m.data.SetDescription("Cumulative of pages scanned")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPrinterUsageScan) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, printerPaperSizeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("printer.paper.size", printerPaperSizeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPrinterUsageScan) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPrinterUsageScan) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPrinterUsageScan(cfg MetricConfig) metricPrinterUsageScan {
	m := metricPrinterUsageScan{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricPrinterCartridgeLeft     metricPrinterCartridgeLeft
	metricPrinterUsageCopy         metricPrinterUsageCopy
	metricPrinterUsagePrint        metricPrinterUsagePrint
	metricPrinterUsageScan         metricPrinterUsageScan
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricPrinterCartridgeLeft:     newMetricPrinterCartridgeLeft(mbc.Metrics.PrinterCartridgeLeft),
		metricPrinterUsageCopy:         newMetricPrinterUsageCopy(mbc.Metrics.PrinterUsageCopy),
		metricPrinterUsagePrint:        newMetricPrinterUsagePrint(mbc.Metrics.PrinterUsagePrint),
		metricPrinterUsageScan:         newMetricPrinterUsageScan(mbc.Metrics.PrinterUsageScan),
		resourceAttributeIncludeFilter: make(map[string]filter.Filter),
		resourceAttributeExcludeFilter: make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.DeviceID.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["device.id"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceID.MetricsInclude)
	}
	if mbc.ResourceAttributes.DeviceID.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["device.id"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceID.MetricsExclude)
	}
	if mbc.ResourceAttributes.DeviceManufacturer.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["device.manufacturer"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceManufacturer.MetricsInclude)
	}
	if mbc.ResourceAttributes.DeviceManufacturer.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["device.manufacturer"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceManufacturer.MetricsExclude)
	}
	if mbc.ResourceAttributes.DeviceModelIdentifier.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["device.model.identifier"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceModelIdentifier.MetricsInclude)
	}
	if mbc.ResourceAttributes.DeviceModelIdentifier.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["device.model.identifier"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceModelIdentifier.MetricsExclude)
	}
	if mbc.ResourceAttributes.DeviceModelName.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["device.model.name"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceModelName.MetricsInclude)
	}
	if mbc.ResourceAttributes.DeviceModelName.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["device.model.name"] = filter.CreateFilter(mbc.ResourceAttributes.DeviceModelName.MetricsExclude)
	}
	if mbc.ResourceAttributes.HostIP.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["host.ip"] = filter.CreateFilter(mbc.ResourceAttributes.HostIP.MetricsInclude)
	}
	if mbc.ResourceAttributes.HostIP.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["host.ip"] = filter.CreateFilter(mbc.ResourceAttributes.HostIP.MetricsExclude)
	}
	if mbc.ResourceAttributes.HostName.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["host.name"] = filter.CreateFilter(mbc.ResourceAttributes.HostName.MetricsInclude)
	}
	if mbc.ResourceAttributes.HostName.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["host.name"] = filter.CreateFilter(mbc.ResourceAttributes.HostName.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	rm.SetSchemaUrl(conventions.SchemaURL)
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricPrinterCartridgeLeft.emit(ils.Metrics())
	mb.metricPrinterUsageCopy.emit(ils.Metrics())
	mb.metricPrinterUsagePrint.emit(ils.Metrics())
	mb.metricPrinterUsageScan.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordPrinterCartridgeLeftDataPoint adds a data point to printer.cartridge.left metric.
func (mb *MetricsBuilder) RecordPrinterCartridgeLeftDataPoint(ts pcommon.Timestamp, val int64, printerCartridgeColorAttributeValue AttributePrinterCartridgeColor) {
	mb.metricPrinterCartridgeLeft.recordDataPoint(mb.startTime, ts, val, printerCartridgeColorAttributeValue.String())
}

// RecordPrinterUsageCopyDataPoint adds a data point to printer.usage.copy metric.
func (mb *MetricsBuilder) RecordPrinterUsageCopyDataPoint(ts pcommon.Timestamp, val int64, printerPaperSizeAttributeValue string) {
	mb.metricPrinterUsageCopy.recordDataPoint(mb.startTime, ts, val, printerPaperSizeAttributeValue)
}

// RecordPrinterUsagePrintDataPoint adds a data point to printer.usage.print metric.
func (mb *MetricsBuilder) RecordPrinterUsagePrintDataPoint(ts pcommon.Timestamp, val int64, printerPaperSizeAttributeValue string) {
	mb.metricPrinterUsagePrint.recordDataPoint(mb.startTime, ts, val, printerPaperSizeAttributeValue)
}

// RecordPrinterUsageScanDataPoint adds a data point to printer.usage.scan metric.
func (mb *MetricsBuilder) RecordPrinterUsageScanDataPoint(ts pcommon.Timestamp, val int64, printerPaperSizeAttributeValue string) {
	mb.metricPrinterUsageScan.recordDataPoint(mb.startTime, ts, val, printerPaperSizeAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
