// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetDeviceID sets provided value as "device.id" attribute.
func (rb *ResourceBuilder) SetDeviceID(val string) {
	if rb.config.DeviceID.Enabled {
		rb.res.Attributes().PutStr("device.id", val)
	}
}

// SetDeviceManufacturerHP sets "device.manufacturer=HP" attribute.
func (rb *ResourceBuilder) SetDeviceManufacturerHP() {
	if rb.config.DeviceManufacturer.Enabled {
		rb.res.Attributes().PutStr("device.manufacturer", "HP")
	}
}

// SetDeviceModelIdentifier sets provided value as "device.model.identifier" attribute.
func (rb *ResourceBuilder) SetDeviceModelIdentifier(val string) {
	if rb.config.DeviceModelIdentifier.Enabled {
		rb.res.Attributes().PutStr("device.model.identifier", val)
	}
}

// SetDeviceModelName sets provided value as "device.model.name" attribute.
func (rb *ResourceBuilder) SetDeviceModelName(val string) {
	if rb.config.DeviceModelName.Enabled {
		rb.res.Attributes().PutStr("device.model.name", val)
	}
}

// SetHostIP sets provided value as "host.ip" attribute.
func (rb *ResourceBuilder) SetHostIP(val string) {
	if rb.config.HostIP.Enabled {
		rb.res.Attributes().PutStr("host.ip", val)
	}
}

// SetHostName sets provided value as "host.name" attribute.
func (rb *ResourceBuilder) SetHostName(val string) {
	if rb.config.HostName.Enabled {
		rb.res.Attributes().PutStr("host.name", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
