// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPrinterCartridgeLeftDataPoint(ts, 1, AttributePrinterCartridgeColorCyan)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPrinterUsageCopyDataPoint(ts, 1, "printer.paper.size-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPrinterUsagePrintDataPoint(ts, 1, "printer.paper.size-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPrinterUsageScanDataPoint(ts, 1, "printer.paper.size-val")

			rb := mb.NewResourceBuilder()
			rb.SetDeviceID("device.id-val")
			rb.SetDeviceManufacturerHP()
			rb.SetDeviceModelIdentifier("device.model.identifier-val")
			rb.SetDeviceModelName("device.model.name-val")
			rb.SetHostIP("host.ip-val")
			rb.SetHostName("host.name-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "printer.cartridge.left":
					assert.False(t, validatedMetrics["printer.cartridge.left"], "Found a duplicate in the metrics slice: printer.cartridge.left")
					validatedMetrics["printer.cartridge.left"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Percent of cartridge left", mi.Description())
					assert.Equal(t, "percent_100", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					printerCartridgeColorAttrVal, ok := dp.Attributes().Get("printer.cartridge.color")
					assert.True(t, ok)
					assert.Equal(t, "cyan", printerCartridgeColorAttrVal.Str())
				case "printer.usage.copy":
					assert.False(t, validatedMetrics["printer.usage.copy"], "Found a duplicate in the metrics slice: printer.usage.copy")
					validatedMetrics["printer.usage.copy"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative of pages copied", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					printerPaperSizeAttrVal, ok := dp.Attributes().Get("printer.paper.size")
					assert.True(t, ok)
					assert.Equal(t, "printer.paper.size-val", printerPaperSizeAttrVal.Str())
				case "printer.usage.print":
					assert.False(t, validatedMetrics["printer.usage.print"], "Found a duplicate in the metrics slice: printer.usage.print")
					validatedMetrics["printer.usage.print"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative of pages printed", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					printerPaperSizeAttrVal, ok := dp.Attributes().Get("printer.paper.size")
					assert.True(t, ok)
					assert.Equal(t, "printer.paper.size-val", printerPaperSizeAttrVal.Str())
				case "printer.usage.scan":
					assert.False(t, validatedMetrics["printer.usage.scan"], "Found a duplicate in the metrics slice: printer.usage.scan")
					validatedMetrics["printer.usage.scan"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative of pages scanned", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					printerPaperSizeAttrVal, ok := dp.Attributes().Get("printer.paper.size")
					assert.True(t, ok)
					assert.Equal(t, "printer.paper.size-val", printerPaperSizeAttrVal.Str())
				}
			}
		})
	}
}
