// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for hp_printers metrics.
type MetricsConfig struct {
	PrinterCartridgeLeft MetricConfig `mapstructure:"printer.cartridge.left"`
	PrinterUsageCopy     MetricConfig `mapstructure:"printer.usage.copy"`
	PrinterUsagePrint    MetricConfig `mapstructure:"printer.usage.print"`
	PrinterUsageScan     MetricConfig `mapstructure:"printer.usage.scan"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PrinterCartridgeLeft: MetricConfig{
			Enabled: true,
		},
		PrinterUsageCopy: MetricConfig{
			Enabled: true,
		},
		PrinterUsagePrint: MetricConfig{
			Enabled: true,
		},
		PrinterUsageScan: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for hp_printers resource attributes.
type ResourceAttributesConfig struct {
	DeviceID              ResourceAttributeConfig `mapstructure:"device.id"`
	DeviceManufacturer    ResourceAttributeConfig `mapstructure:"device.manufacturer"`
	DeviceModelIdentifier ResourceAttributeConfig `mapstructure:"device.model.identifier"`
	DeviceModelName       ResourceAttributeConfig `mapstructure:"device.model.name"`
	HostIP                ResourceAttributeConfig `mapstructure:"host.ip"`
	HostName              ResourceAttributeConfig `mapstructure:"host.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		DeviceID: ResourceAttributeConfig{
			Enabled: true,
		},
		DeviceManufacturer: ResourceAttributeConfig{
			Enabled: true,
		},
		DeviceModelIdentifier: ResourceAttributeConfig{
			Enabled: true,
		},
		DeviceModelName: ResourceAttributeConfig{
			Enabled: true,
		},
		HostIP: ResourceAttributeConfig{
			Enabled: true,
		},
		HostName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for hp_printers metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
