// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetDeviceID("device.id-val")
			rb.SetDeviceManufacturerHP()
			rb.SetDeviceModelIdentifier("device.model.identifier-val")
			rb.SetDeviceModelName("device.model.name-val")
			rb.SetHostIP("host.ip-val")
			rb.SetHostName("host.name-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 6, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 6, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}
			deviceIDAttrVal, ok := res.Attributes().Get("device.id")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "device.id-val", deviceIDAttrVal.Str())
			}
			deviceManufacturerAttrVal, ok := res.Attributes().Get("device.manufacturer")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "HP", deviceManufacturerAttrVal.Str())
			}
			deviceModelIdentifierAttrVal, ok := res.Attributes().Get("device.model.identifier")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "device.model.identifier-val", deviceModelIdentifierAttrVal.Str())
			}
			deviceModelNameAttrVal, ok := res.Attributes().Get("device.model.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "device.model.name-val", deviceModelNameAttrVal.Str())
			}
			hostIPAttrVal, ok := res.Attributes().Get("host.ip")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.ip-val", hostIPAttrVal.Str())
			}
			hostNameAttrVal, ok := res.Attributes().Get("host.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.name-val", hostNameAttrVal.Str())
			}
		})
	}
}
